server:
  port: 10011
spring:
  application:
    name: zipkin

eureka:
  client:
    service-url:
      defaultZone: http://root123:root123@127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1

logging:
  level:
    org.springframework.web: DEBUG,CONSOLE
