server:
  port: 10010
spring:
  application:
    name: gateway
  zipkin:
    enabled: true
    base-url: http://127.0.0.1:10011
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #从注册中心寻找
      routes:
        - id: hystrix_route
          uri: lb://web-service   #web微服务
          predicates:
            - Path=/api/web/**    #访问微服务的路径
          filters:
            - StripPrefix=2       #去除两个前缀目录

eureka:
  client:
    region: beijing
    availability-zones:
      beijing: zone-1
    service-url:
      zone-1: http://root123:root123@127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    metadata-map:
      zone: zone-1

zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    user-service: /user/**  #商品微服务
    web-service: /web/**
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials #匹配禁止使用的头信息，这里设置为null，否则set-cookie无效


ribbon:
  ConnectTimeout: 400000 # 连接超时时间(ms)
  ReadTimeout: 200000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
logging:
  level:
    org.springframework.web: DEBUG,CONSOLE
    io.netty: debug
management:
  metrics:
    web:
      server:
        auto-time-requests: false
